### ISSUE TITLE
Chauffeur seems to crash if you use `App_Code`

### ISSUE THREAD

**Issue by aaronpowell** [aaronpowell/Chauffeur#28]
Have a site with some .cs in `App_Code` and Chauffeur crashed. Really don't think you should use `App)_Code` but still...

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'App_Code' or one of its dependencies. The system cannot find the file specified.
at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
at System.Reflection.Assembly.Load(String assemblyString)
at Umbraco.Core.TypeFinder.GetAllAssemblies()
at Umbraco.Core.TypeFinder.GetFilteredAssemblies(IEnumerable`1 excludeFromResults, String[] exclusionFilter)
at Umbraco.Core.TypeFinder.GetAssembliesWithKnownExclusions(IEnumerable`1 excludeFromResults)
at Chauffeur.ShittyIoC..ctor()
at Chauffeur.Host.UmbracoHost..ctor(TextReader reader, TextWriter writer)
at Chauffeur.Runner.Program.Main(String[] args)
at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
at System.AppDomain.ExecuteAssembly(String assemblyFile, String[] args)
at System.AppDomain.ExecuteAssembly(String assemblyFile, String[] args)
at Chauffeur.Runner.Program.Main(String[] args)
```

**Comment by aaronpowell** [comment]
Closing as Chauffeur really doesn't fit in a model where you're using uncompiled code.
