### ISSUE TITLE
IndexOutOfRangeException after upgrading to V1.1

### ISSUE THREAD

**Issue by dinc5150** [aaronpowell/Chauffeur#72]
Hey Aaron, 
Just upgraded to V1.1 against Umbraco  7.11.1 and getting an error when running any command (including `help`). Tested an upgrade on a couple of sites both with the same results.

Downgraded to 1.0 and works fine . 

The error is below. Let me know if you need any more details

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Chauffeur.Host.UmbracoHost.<Process>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Chauffeur.Host.UmbracoHost.<Run>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Chauffeur.Runner.Program.Main(String[] args)
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, String[] args)
   at Chauffeur.Runner.Program.Main(String[] args)
```

**Comment by aaronpowell** [comment]
Ah I haven't tested with `7.11` yet, might be something with the new user stuff for create user. I'll have a lok into it.

**Comment by aaronpowell** [comment]
Ok, turns out it's nothing to do with `7.11`, but my cli parser is completely broken and my integration tests aren't actually causing build failures!

Just cutting a release now 😃

**Comment by aaronpowell** [comment]
Ok, I've cut version [1.1.1](https://www.nuget.org/packages/Chauffeur/1.1.1) which should fix the problem. Let me know how it goes!

**Comment by dinc5150** [comment]
At least you have tests!

Just gave it a spin and worked perfectly. Thanks!
