### ISSUE TITLE
Chauffeur 1.4.1 with umbraco 7.14.0 - cant find core

### ISSUE THREAD

**Issue by stuartcrouch** [aaronpowell/Chauffeur#97]
## What went wrong?

Chauffeur.Runner.exe

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Umbraco.Core, Version=1.0.6611.19702, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at Chauffeur.ShittyIoC..ctor()
   at Chauffeur.Host.UmbracoHost..ctor(TextReader reader, TextWriter writer)
   at Chauffeur.Runner.Program.Main(String[] args)
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, String[] args)
   at Chauffeur.Runner.Program.Main(String[] args)

## What should have happened?

I would have expected umbraco to install and the db to be full of tables

## How can I reproduce the issue?

Downloaded umbraco 7.14.0 with the plan to install umbraco and update to a certain db state using chauffeur and usync.chauffeur
Downloaded chauffeur.runner 1.4.1
Added a SQL database to the web.config.
Launched Chauffeur.Runner.exe install

_Feel free to drop the path & connection string, I'm most interested in the versions._

## Anything else you can think of

* Did you receive any error messages/stack traces?
* If you're using the `Delivery` feature, can you provide the `Delivery` that it errors on?
* Are you able to create a repo that I can see the error in action?

**Comment by aaronpowell** [comment]
Hmm I wonder if there's something changed in `7.14` that introduces a new API or a changed interface.
